# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: referredin

test:
  adapter: postgresql
  database: referredin_test

production:
  adapter: postgresql
  database: referredin_production
